/**
 * Export module
 * Handles exporting to various formats (PNG, SVG, ASCII, CSS)
 */

import { getActiveImage, renderToCanvas } from './canvas.js';
import { getControls, getExportDimensions } from './controls.js';
import { showToast } from './utils.js';

/**
 * Initialize export button event listeners
 */
export function initExport() {
  document.getElementById('exportPng').addEventListener('click', exportPng);
  document.getElementById('topExportBtn').addEventListener('click', exportPng);
  document.getElementById('exportSvg').addEventListener('click', exportSvg);
  document.getElementById('exportAscii').addEventListener('click', exportAscii);
  document.getElementById('exportCss').addEventListener('click', exportCss);
}

/**
 * Calculate luminance from RGB values
 */
function lum(r, g, b) {
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

/**
 * Fit image within target dimensions (cover mode)
 */
function fitImage(img, tw, th) {
  const ir = img.width / img.height;
  const tr = tw / th;
  let dw, dh, ox, oy;
  
  if (ir > tr) {
    dh = th;
    dw = dh * ir;
    ox = (tw - dw) / 2;
    oy = 0;
  } else {
    dw = tw;
    dh = dw / ir;
    ox = 0;
    oy = (th - dh) / 2;
  }
  
  return { dw, dh, ox, oy };
}

/**
 * Track download event with Umami
 */
function trackDownload(format, dimensions = null) {
  if (window.umami) {
    const eventData = { format };
    if (dimensions) {
      eventData.dimensions = dimensions;
    }
    window.umami.track('download', eventData);
  }
}

/**
 * Export as PNG
 */
function exportPng() {
  const activeImage = getActiveImage();
  if (!activeImage || !activeImage.complete || !activeImage.naturalWidth) {
    showToast('Upload an image first');
    return;
  }
  
  const { width, height } = getExportDimensions();
  const exportCanvas = document.createElement('canvas');
  exportCanvas.width = width;
  exportCanvas.height = height;
  
  renderToCanvas(exportCanvas, width, height);
  
  const a = document.createElement('a');
  a.href = exportCanvas.toDataURL('image/png');
  a.download = `extra-dotted-portrait-${width}x${height}.png`;
  a.click();
  
  // Track download
  trackDownload('PNG', `${width}x${height}`);
  
  showToast(`PNG exported at ${width}×${height}px`);
}

/**
 * Export as SVG
 */
function exportSvg() {
  const activeImage = getActiveImage();
  if (!activeImage || !activeImage.complete || !activeImage.naturalWidth) {
    showToast('Upload an image first');
    return;
  }
  
  const { width, height } = getExportDimensions();
  const eo = document.createElement('canvas');
  eo.width = width;
  eo.height = height;
  const eoc = eo.getContext('2d', { willReadFrequently: true });
  
  const fit = fitImage(activeImage, width, height);
  eoc.drawImage(activeImage, fit.ox, fit.oy, fit.dw, fit.dh);
  const data = eoc.getImageData(0, 0, width, height).data;
  
  const controls = getControls();
  const { gap, scale, contrast, toneColor, colorMode } = controls;
  const useSrc = colorMode === 'source';
  
  let circles = '';
  
  for (let y = 0; y < height; y += gap) {
    for (let x = 0; x < width; x += gap) {
      const i = (y * width + x) * 4;
      const r = data[i] || 0;
      const g = data[i + 1] || 0;
      const b = data[i + 2] || 0;
      const a = data[i + 3] || 0;
      
      if (a < 16) continue;
      
      const l = lum(r, g, b) / 255;
      const m = Math.min(1, Math.max(0, (1 - l - 0.5) * contrast + 0.5));
      const rad = Math.max(0, m * (gap * 0.46) * scale);
      
      if (rad < 0.28) continue;
      
      const col = useSrc 
        ? `rgba(${r},${g},${b},${Math.max(0.26, m).toFixed(3)})` 
        : toneColor;
      circles += `<circle cx="${(x + gap / 2).toFixed(1)}" cy="${(y + gap / 2).toFixed(1)}" r="${rad.toFixed(2)}" fill="${col}"/>`;
    }
  }
  
  const svgStr = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">
<!-- Generated by Extra Dotted -->
${circles}
</svg>`;
  
  const blob = new Blob([svgStr], { type: 'image/svg+xml' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `extra-dotted-portrait-${width}x${height}.svg`;
  a.click();
  
  setTimeout(() => URL.revokeObjectURL(url), 3000);
  
  // Track download
  trackDownload('SVG', `${width}x${height}`);
  
  showToast(`SVG exported at ${width}×${height}px`);
}

/**
 * Export as ASCII/Unicode art
 */
function exportAscii() {
  const activeImage = getActiveImage();
  if (!activeImage || !activeImage.complete || !activeImage.naturalWidth) {
    showToast('Upload an image first');
    return;
  }
  
  const cols = 100;
  const aspect = activeImage.height / activeImage.width;
  const rows = Math.round(cols * aspect * 0.46); // chars are taller than wide
  
  const tmp = document.createElement('canvas');
  tmp.width = cols;
  tmp.height = rows;
  const tc = tmp.getContext('2d');
  tc.drawImage(activeImage, 0, 0, cols, rows);
  const data = tc.getImageData(0, 0, cols, rows).data;
  
  const chars = [' ', '·', '⠂', '░', '▒', '▓', '█'];
  let out = '';
  
  for (let y = 0; y < rows; y++) {
    for (let x = 0; x < cols; x++) {
      const i = (y * cols + x) * 4;
      const l = lum(data[i], data[i + 1], data[i + 2]) / 255;
      const idx = Math.floor(l * (chars.length - 1));
      out += chars[idx];
    }
    out += '\n';
  }
  
  document.getElementById('asciiOutput').textContent = out;
  document.getElementById('asciiModal').style.display = 'block';
  
  // Track download
  trackDownload('ASCII', `${cols}x${rows}`);
}

/**
 * Export as CSS snippet
 */
function exportCss() {
  const activeImage = getActiveImage();
  if (!activeImage || !activeImage.complete || !activeImage.naturalWidth) {
    showToast('Upload an image first');
    return;
  }
  
  const cols = 16;
  const rows = 16;
  const tmp = document.createElement('canvas');
  tmp.width = cols;
  tmp.height = rows;
  const tc = tmp.getContext('2d');
  tc.drawImage(activeImage, 0, 0, cols, rows);
  const data = tc.getImageData(0, 0, cols, rows).data;
  
  const controls = getControls();
  const { gap, scale, toneColor, colorMode } = controls;
  const useSrc = colorMode === 'source';
  
  const gradients = [];
  
  for (let y = 0; y < rows; y++) {
    for (let x = 0; x < cols; x++) {
      const i = (y * cols + x) * 4;
      const r = data[i] || 0;
      const g = data[i + 1] || 0;
      const b = data[i + 2] || 0;
      const a = data[i + 3] || 0;
      
      if (a < 16) continue;
      
      const l = lum(r, g, b) / 255;
      const m = Math.min(1, Math.max(0, 1 - l));
      const radius = Math.round(m * 46 * scale);
      
      if (radius < 1) continue;
      
      const col = useSrc ? `rgb(${r},${g},${b})` : toneColor;
      const posX = ((x / cols) * 100).toFixed(1) + '%';
      const posY = ((y / rows) * 100).toFixed(1) + '%';
      gradients.push(`  radial-gradient(circle ${radius}% at ${posX} ${posY}, ${col} 0%, transparent 100%)`);
    }
  }
  
  const css = `.hero-bg {
  background-image:
${gradients.join(',\n')};
  background-size: ${gap * cols}px ${gap * rows}px;
  /* Generated by Extra Dotted — tweak background-size to adjust density */
}`;
  
  document.getElementById('cssOutput').textContent = css;
  document.getElementById('cssModal').style.display = 'block';
  
  // Track download
  trackDownload('CSS', `${cols}x${rows}`);
}
